---
manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
    default_ttl: 120
    enforce_order: True
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN

zones:
  jeffreyharmon.dev.:
    sources:
      - config
    targets:
      - cloudflare
    
  pear.cx.:
    sources:
      - config
    targets:
      - cloudflare
