name: deploy

on:
  push:
    branches:
      - main

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3"
      - name: Install OctoDNS
        run: pip install 'octodns==1.13.0' octodns_cloudflare
      - name: Sync w/ production DNS providers
        run: ./bin/sync
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
